### ISSUE TITLE
Sugerencia ortográfica

### ISSUE THREAD

**Issue by zentree** [pachadotdev/chilemapas#1]
Sería excelente que los nombres de comuna, provincia y región tuvieran los acentos, eñes, etc. Si complica desde un punto de vista de localización, sugiero agregar columnas como nombre_comuna_sp a la tabla códigos territoriales.

**Comment by pachadotdev** [comment]
Hola

Creo que complica más de lo que uno pudiera creer.
Por eso uso el codigo de comuna en todos los datasets.
Podría agregar una función que detecte la codificación del sistema
operativo y según eso aplique expresiones regulares.

Saludos!!

**Comment by zentree** [comment]
Entiendo y comparto que las operaciones de R van a ser más consistentes entre sistemas operativos si son efectuadas usando códigos numéricos o caracteres básicos de ascii. Mi punto es que cuando uno va a label (¿etiquetar?) los mapas (por ejemplo nombre de comunas) ahí sería mejor tener un campo que contenga la ortografía apropiada.

Creo que funcionaría bien en la _mayoría_ de los sistemas de la población de usuarios. La situación actual es que quedamos con la ortografía incorrecta en _todos_ los sistemas. Como siempre, la funcionalidad por defecto domina el resultado final (es cosa de ver la multitud de mapas ggplot con fondo gris y números pequeños de bajo contraste): mapas con nombres incorrectos pasan a ser la mayoría. Cambiar nombres a mano es posible, pero poco eficiente.

**Comment by pachadotdev** [comment]
Hola

Sí, por lo mismo prefiero hacer una funcion que se llame reetiquetar() y
que haga algo de este estilo

```
if (sistema == "Windows") {
    datos %>% mutate(comuna = vector_en_iso_8859)
} else {
     datos %>% mutate(comuna = vector_en_utf8)
}
```

así logramos lo mismo de las etiquetas pero de modo que distintos sistemas
entiendan que algo como \u00e9 es un caracter acentuado y no un "<xe9>"


—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by zentree** [comment]
OK. Creo que ahora entendí tu comentario anterior, gracias por el detalle. Estuve jugando un poco con chilemapas y ahí me van surgiendo dudas, ideas etc. Si me pongo muy latero me avisas nomás.

**Comment by pachadotdev** [comment]
latero? son ideas que ayudan !!!!

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by pachadotdev** [comment]
hola @zentree 
he implementado la idea de usar verbos para los nombres de las funciones que fusionan áreas
también pasé todo a `theme_minimal` y agregué datos por zona
me falta pensar una función para re-etiquetar

**Comment by zentree** [comment]
Voy a actualizar mi instalación de chilemapas, ya veo en github que hay funciones generar_. Muchas gracias.
