### ISSUE TITLE
Nombre de las zonas 

### ISSUE THREAD

**Issue by ignacioalbornoz** [pachadotdev/chilemapas#13]
Hola, estaría bueno agregar una columna con el nombre de las zonas para poder filtrar por nombre. Saludos :)

**Comment by pachadotdev** [comment]
hola @ignacioalbornoz, tienes mas indicaciones de la idea?
aca tengo el procesamiento de las zonas en la cartografia https://github.com/pachadotdev/censo2017-cartografias/blob/main/13-zonas.R
o te refieres a las tablas censales?

**Comment by pachadotdev** [comment]
la tabla de zonas viene asi https://github.com/pachadotdev/censo2017/blob/main/data-raw/00-create-local-db-sqlite.R#L188

**Comment by ignacioalbornoz** [comment]
Por ejemplo en https://github.com/pachadotdev/chilemapas/blob/master/data_geojson/zonas/r08.geojson, al hacer click en Pehuén, aparece su geocodigo, codigo_comuna, codigo_provincia, codigo_region. Sería util para estas zonas menores poder hacer querys con su nombre y que retornen estos datos, en especial su geocódigo, ya que ya hay una tabla que relaciona el geocódigo con las otras 3 columnas.

**Comment by pachadotdev** [comment]
hola @ignacioalbornoz 

disculpa la demora, lo que dices se puede hacer asi

```
library(chilemapas)
library(dplyr)
library(ggplot2)

zona_ejemplo <- mapa_zonas %>% 
  left_join(codigos_territoriales) %>% 
  filter(nombre_comuna == "Valdivia")

comuna_ejemplo <- mapa_comunas %>% 
  left_join(codigos_territoriales) %>% 
  filter(nombre_comuna == "Valdivia")

ggplot() +
  geom_sf(data = comuna_ejemplo, aes(geometry = geometry), alpha = 0.5,
          fill = "blue") +
  geom_sf(data = zona_ejemplo, aes(geometry = geometry), alpha = 0.5,
          fill = "yellow")
```

![image](https://user-images.githubusercontent.com/10091065/173474576-6570b249-c4d2-4a8e-bbda-4a031b575e73.png)

las zonas que se ven amarillas son debido al error de interpolacion (estos mapas estan simplificados al limite)
