### ISSUE TITLE
Link a documentación erroneo

### ISSUE THREAD

**Issue by pabecerra** [pachadotdev/chilemapas#3]
Estimado,
El link de la documentación aún apunta a su anterior dominio https://pacha.hk/chilemapas, el cual ya no funciona. Por favor actualizar al nuevo https://pacha.dev/chilemapas/.

**Comment by pachadotdev** [comment]
mejor aún, en cuanto la red me deje hacer push, cambio a https://pachamaltese.github.io/chilemapas/
