### ISSUE TITLE
Libreria faltante en Ubuntu

### ISSUE THREAD

**Issue by edovt** [pachadotdev/chilemapas#5]
Hola, estaba instalando el paquete en Ubuntu 20.04 y me apareció que hay una librería faltante, libjq, por lo que creo que habría que agregar `libjq-dev` a las instrucciones de instalación.

Saludos!

**Comment by pachadotdev** [comment]
gracias @edovtp 
no logro replicar el error en Ubuntu 20.04, voy a reinstalar en una máquina virtual sin mi setup

**Comment by pachadotdev** [comment]
@edovtp listo, lo repliqué y vendrá con el cambio en la documentación de la v0.3
