### ISSUE TITLE
Problema combinando mapas de zonas y comunas

### ISSUE THREAD

**Issue by sfloresalvarado** [pachadotdev/chilemapas#7]
Traté de crear un mapa que contuviera contornos de comuna y de zonas censales, combinando ambos sets. Sin embargo, éstos no calzan en la mayor parte de las comunas en que hice el intento. El mapa de zonas censales aparece mucho más pequeño que el de las comunas. No sé si fue un error mío o un error en el paquete. Dejo un ejemplo de este problema:

```
library(chilemapas)
library(tidyverse)

mapa_zonas %>% 
  filter(codigo_comuna == "02301") %>% 
  mutate(geometry_zona = geometry) %>% 
  select(codigo_comuna, geometry_zona) %>% 
  left_join(mapa_comunas %>% 
                filter(codigo_comuna == "02301"), by = "codigo_comuna") %>% 
  ggplot() +
  geom_sf(aes(geometry = geometry), size = 0.1) +
  geom_sf(aes(geometry = geometry_zona), size = 0.1) 
```

**Comment by pachadotdev** [comment]
hola

no siempre coinciden las zonas con las comunas, muchas veces las comunas contienen territorios no habitados (e.g. San José de Maipo)

adjunto ejemplo de Tocopilla vs Santiago:
```
library(chilemapas)
library(tidyverse)

ggplot() +
  geom_sf(data = mapa_comunas %>% filter(codigo_comuna == "02301"),
    aes(geometry = geometry), size = 0.1, fill = NA) +
  geom_sf(data = mapa_zonas %>% filter(codigo_comuna == "02301"),
    aes(geometry = geometry), size = 0.1, fill = NA) 

ggplot() +
  geom_sf(data = mapa_comunas %>% filter(codigo_comuna == "13101"),
          aes(geometry = geometry), size = 0.1, fill = NA) +
  geom_sf(data = mapa_zonas %>% filter(codigo_comuna == "13101"),
          aes(geometry = geometry), size = 0.1, fill = NA) 
```

**Comment by sfloresalvarado** [comment]
Gracias! justamente fue la comparación con la RM la que me generó la duda, pero sabiendo que lo esperado es que sea así, me quedo más tranquila. 

Saludos

**Comment by pachadotdev** [comment]
> Gracias! justamente fue la comparación con la RM la que me generó la duda, pero sabiendo que lo esperado es que sea así, me quedo más tranquila.
> 
> Saludos
buenas noches
no hay problema, tengo los datos en bruto si los llegara a necesitar
cualquier duda me vuelve a escribir
