### ISSUE TITLE
Mapas 2017 (sin Ñuble)

### ISSUE THREAD

**Issue by sfloresalvarado** [pachadotdev/chilemapas#9]
Estimado Pacha, además de agradecerte por este paquete que es de muchísima utilidad, te escribo por un pequeño problema para el que puede que tengas una solución más eficiente que lo que yo podría hacer desde cero:

Estoy trabajando con datos del censo 2017 y los mapas de chilemapas a nivel de zona censal y comuna, sin embargo, tengo problemas con las comunas ya que los códigos no coinciden con los de las comunas del censo para la actual región de Ñuble. 

En la descripción del paquete dice "Mapas administrativos: Construi el mapa de la Region de Niuble haciendo todas las transformaciones correspondientes sobre la Region del Bio Bio. Otro aporte es el mapa de servicios de salud recopilando datos de diversas fuentes.". Entiendo a patir de esto que, además de los mapas disponibles, cuentas con ellos utilizando las divisiones administrativas previas. Quería consultarte, entonces, si te es posible subir la versión de los mapas compatibles con el censo 2017 o si tienes una función o la lista de conversiones necesarias para llegar de una versión a otra.

Saludos y gracias desde ya!

**Comment by pachadotdev** [comment]
hola @Shandu99 , disculpa la demora, he tenido muchos problemas con el laptop 
se me ocurre que sería mejor crear una función a partir de lo que hay en https://github.com/ropensci/censo2017-cartografias, de manera tal que se obtenga una biyección entre los códigos del censo (que están en dos versiones) 
o también se podría agregar un parámetro tipo `nuble = F`, pues efectivamente las divisiones anteriores las tengo en algún disco externo

**Comment by pachadotdev** [comment]
el detalle línea por línea de lo que hice está en https://github.com/pachadotdev/chilemapas/blob/master/data_processing/02_communes_map.R#L71
si se fija chilemapas es antiguo y creo que le ha servido a mucha gente, pero me he movido 100% a mis temas centrales pues yo dejé voluntariamente casi toda actividad en espaniol, cerré con el paquete `censo2017` y realmente no tengo las ganas de aportar en un entorno donde todos son "enemigos", "fachos" o "comunistas" y el que gana es el que grita más fuerte o el que dice la estupidez más grande... hasta que no se recupere (espero) la noción de que todos somos personas, acepto PRs que veré en mi tiempo libre y haré los retoques para que chilemapas siga en CRAN

**Comment by sfloresalvarado** [comment]
Hola @pachadotdev ! Muchas gracias por tu respuesta. Efectivamente partí por descartar la comuna de Ñuble para no tener problemas, y por ahora he estado trabajando de esa forma, sin embargo sería ideal poder contar con toda la información y no tener que descartarla, así que revisaré esos links que me compartes para ver si puedo resolver el problema. 

Respecto a lo último que comentas, lamento que te haya tocado trabajar en un entorno tan desagradable. No sé si tiene que ver con el área de trabajo en particular en la que de desenvuelves (desconozco cuál es), ya que yo no he tenido ese tipo de experiencias pese a lo convulsionado del ambiente político. Espero, de todos modos, que la situación mejore y eventualmente vuelvas a trabajar en ese paquete u otros similares. Aprovecho para agradecerte ya que creo que tanto `censo2017` como `chilemapas` son excelentes trabajos, y de hecho este año empecé a utilizarlos al dar clases sobre trabajo con datos espaciales en R.

Saludos!

**Comment by pachadotdev** [comment]
> Hola @pachadotdev ! Muchas gracias por tu respuesta. Efectivamente partí por descartar la comuna de Ñuble para no tener problemas, y por ahora he estado trabajando de esa forma, sin embargo sería ideal poder contar con toda la información y no tener que descartarla, así que revisaré esos links que me compartes para ver si puedo resolver el problema.
> 
> Respecto a lo último que comentas, lamento que te haya tocado trabajar en un entorno tan desagradable. No sé si tiene que ver con el área de trabajo en particular en la que de desenvuelves (desconozco cuál es), ya que yo no he tenido ese tipo de experiencias pese a lo convulsionado del ambiente político. Espero, de todos modos, que la situación mejore y eventualmente vuelvas a trabajar en ese paquete u otros similares. Aprovecho para agradecerte ya que creo que tanto `censo2017` como `chilemapas` son excelentes trabajos, y de hecho este año empecé a utilizarlos al dar clases sobre trabajo con datos espaciales en R.
> 
> Saludos!

muchas gracias !! dandole una segunda vuelta, puedo crear un branch separado con la cartografia actualizada ... creo que asi ganamos todos

**Comment by pachadotdev** [comment]
hola @Shandu99 

como esto es para educación, acabo de integrar la PR #10 donde cree una tabla para hacer el match, o sea que uno trabaja normalmente con `censo2017` con los codigos con 15 regiones y luego usa la tabla `codigos_territoriales_16r` de `chilemapas` que le hace el match con los códigos de 16 regiones.

para instalar la nueva version de chilemapas (0.2 -> 0.2.1) hay que hacer esto pues no estará en CRAN en el corto plazo
```
if (!require("remotes")) install.packages("remotes")
remotes::install_github("pachadotdev/chilemapas")
```

luego sería más o menos así
```
library(censo2017)
library(dplyr)
library(ggplot2)
library(chilemapas)

nivel_educacional_biobio_niuble <- tbl(censo_conectar(), "zonas") %>% 
  mutate(
    region = substr(as.character(geocodigo), 1, 2),
    comuna = substr(as.character(geocodigo), 1, 5)
  ) %>% 
  filter(region == "08") %>% 
  select(comuna, geocodigo, zonaloc_ref_id) %>%
  inner_join(select(tbl(censo_conectar(), "viviendas"), zonaloc_ref_id, vivienda_ref_id), by = "zonaloc_ref_id") %>%
  inner_join(select(tbl(censo_conectar(), "hogares"), vivienda_ref_id, hogar_ref_id), by = "vivienda_ref_id") %>%
  inner_join(select(tbl(censo_conectar(), "personas"), hogar_ref_id, nivel_educ = p15), by = "hogar_ref_id") %>%
  collect()

censo_desconectar()

nivel_educacional_biobio_niuble <- nivel_educacional_biobio_niuble %>% 
  group_by(comuna, nivel_educ) %>%
  summarise(cuenta = n()) %>%
  group_by(comuna) %>%
  mutate(proporcion = cuenta / sum(cuenta))

# ACÁ CONVIERTO LOS RESULTADOS CENSALES A CODIGOS DE 16 REGIONES
nivel_educacional_biobio_niuble <- nivel_educacional_biobio_niuble %>% 
  filter(nivel_educ == 12) %>% 
  left_join(codigos_territoriales_16r, 
            by = c("comuna" = "codigo_comuna")) %>% 
  mutate(
    comuna = case_when(
      is.na(codigo_comuna_16r) ~ comuna,
      TRUE ~ codigo_comuna_16r
    )
  )

mapa_biobio_niuble <- mapa_comunas %>% 
  filter(codigo_region %in% c("08", "16")) %>% 
  left_join(nivel_educacional_biobio_niuble, by = c("codigo_comuna" = "comuna"))

mapa_biobio_niuble %>% 
  filter(is.na(proporcion))

colors <- c("#DCA761","#C6C16D","#8B9C94","#628CA5","#5A6C7A")

g <- ggplot() +
  geom_sf(data = mapa_biobio_niuble %>% # 4TO CAMBIO
            select(codigo_comuna = codigo_comuna, geometry) %>% # 5TO CAMBIO
            left_join(
              mapa_biobio_niuble %>% 
                select(codigo_comuna, nivel_educ, proporcion),
              by = "codigo_comuna"
            ),
          aes(fill = proporcion, geometry = geometry),
          size = 0.1) +
  scale_fill_gradientn(colours = rev(colors), name = "Porcentaje") +
  labs(title = "Porcentaje de habitantes con titulo profesional\npor comuna en la Region del Bio Bio y Niuble") + # 3ER CAMBIO
  theme_minimal(base_size = 13)

g
```

![image](https://user-images.githubusercontent.com/10091065/132260917-e76470c8-b86d-47ff-9e2c-d3f6eeb03861.png)

la referencia es https://docs.ropensci.org/censo2017/articles/censo2017.html y https://ropensci.org/blog/2021/07/27/censo2017-es/

**Comment by sfloresalvarado** [comment]
Muchas gracias por la actualización!
